name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Grant permissions required for Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create .nojekyll at repo root
        run: echo "" > .nojekyll

      # Create .env from GitHub Secrets (recommended). Add these secrets in repo Settings -> Secrets -> Actions
      - name: Create .env from Secrets
        run: |
          echo "REACT_APP_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund || npm install --legacy-peer-deps

      - name: Build
        env:
          CI: false
        run: npm run build

      - name: Ensure .nojekyll in build
        run: echo "" > build/.nojekyll

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1